# Redirect HTTP → HTTPS
server {
    listen 80;
    server_name adityabijapurkar.in www.adityabijapurkar.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name adityabijapurkar.in www.adityabijapurkar.in;

    ssl_certificate     /etc/ssl/cloudflare/cert.pem;
    ssl_certificate_key /etc/ssl/cloudflare/key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    # FE static files
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # BE redirection
    location ~ ^/(api|actuator)/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    # Auth redirection
    # location ~ ^(auth)/ {
    #     proxy_pass http://auth:8080;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Forwarded-For $remote_addr;
    # }

}
