name: Deploy to remote instance from Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check if nginx.conf file changed
      id: compose_check
      run: |
        if git diff --name-only HEAD^ HEAD | grep -Eq "^(nginx/nginx\.conf|nginx/Dockerfile)$"; then
          echo "file_changed=true" >> $GITHUB_OUTPUT
        else
          echo "file_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      if: steps.compose_check.outputs.file_changed == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: steps.compose_check.outputs.file_changed == 'true'
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push to Docker image to aditya-resume-nginx
      if: steps.compose_check.outputs.file_changed == 'true'
      run: |
        IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NGINX }}:latest
        docker buildx build -f nginx/Dockerfile --platform linux/amd64 -t $IMAGE_NAME --push .

    - name: Deploy to remote instance
      if: steps.compose_check.outputs.file_changed == 'true'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IPV4 }}
        username: ${{ secrets.INSTANCE_USER }}
        key: ${{ secrets.INSTANCE_KEY }}
        script: |
          set -e
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NGINX }}:latest
          echo "pulling the latest image from docker hub"
          sudo docker pull $IMAGE
          echo "restarting the nginx container..."
          sudo docker compose up -d nginx
          echo "removing unused image..."
          sudo docker image prune -f
          echo "successfully completed nginx restart script!"